### ISSUE TITLE
[bug] Is Loading displayed somehow

### ISSUE THREAD

**Issue by haoyangw** [cs3216-a3-group-4/assignment-3#163]
After registering and just before onboarding page is displayed, 'Is Loading' text is displayed, left-aligned, on the screen for a split second. Unfortunately(or fortunately) the text disappears very quickly once onboarding page is rendered, so unable to discern what component is rendering the 'Is Loading' text

**Comment by seelengxd** [comment]
> component is rendering the 'Is Loading' text

https://github.com/cs3216-a3-group-4/assignment-3/blob/main/frontend/components/layout/app-layout.tsx#L35
