### ISSUE TITLE
[feat]: implement stripe integration (backend)

### ISSUE THREAD

**Issue by chloeelim** [cs3216-a3-group-4/assignment-3#171]

**Comment by seelengxd** [comment]
estimates from previous meeting: subscription flow by today (17 Oct), the webhooks/cancellation/downgrade flow in 2-3 days (20 Oct?)

**Comment by chloeelim** [comment]
thanks @haoyangw  🎉 

https://github.com/cs3216-a3-group-4/assignment-3/pull/251
