### ISSUE TITLE
[bug]: infinite loading animation

### ISSUE THREAD

**Issue by haoyangw** [cs3216-a3-group-4/assignment-3#187]
When accessing /notes page without logging in, the loading animation gets stuck and the page doesn't redirect to the landing page at all:

![image](https://github.com/user-attachments/assets/98778355-b6b2-42f5-ab15-98ff79e27bf0)

**Comment by seelengxd** [comment]
note, this bug is there for EVERY authenticated route. it happens when ur not authenticated
